blank_issues_enabled: false
contact_links:
  - name: Leave a Marketplace review
    url: https://marketplace.visualstudio.com/items?itemName=jiwan-dev.git-metrics-dashboard&ssr=false#review-details
    about: Please share feedback as a review instead of an issue if it's not a bug or feature request.
